"""initial schema

Revision ID: 8fe826efa40f
Revises: 
Create Date: 2026-05-02 14:58:45.113423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fe826efa40f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('magic_link_token', sa.String(length=255), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'paid', name='user_plan'), nullable=False),
    sa.Column('signup_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maps_url', sa.String(length=1024), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('ig_handle', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_tier', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'past_due', name='subscription_status'), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='audit_status'), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', name='audit_trigger'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_business_id'), ['business_id'], unique=False)

    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maps_url', sa.String(length=1024), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_business_id'), ['business_id'], unique=False)

    op.create_table('audit_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('maps', 'website', 'instagram', 'nap', 'competitors', name='audit_section_name'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('done', 'failed', 'partial', name='audit_section_status'), nullable=False),
    sa.Column('raw_data_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_sections_audit_id'), ['audit_id'], unique=False)

    op.create_table('competitor_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_observations_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_observations_competitor_id'), ['competitor_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('maps', 'website', 'instagram', 'nap', 'competitors', name='audit_section_name'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='recommendation_severity'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('estimated_impact', sa.String(length=64), nullable=True),
    sa.Column('estimated_time', sa.String(length=64), nullable=True),
    sa.Column('fix_status', sa.Enum('open', 'done', 'dismissed', name='recommendation_fix_status'), nullable=False),
    sa.Column('marked_done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_audit_id'), ['audit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_audit_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('competitor_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_observations_competitor_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_observations_audit_id'))

    op.drop_table('competitor_observations')
    with op.batch_alter_table('audit_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_sections_audit_id'))

    op.drop_table('audit_sections')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_business_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_business_id'))

    op.drop_table('audits')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))

    op.drop_table('businesses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

    # Postgres creates a native TYPE for each named Enum column; drop_table
    # leaves those types behind, so a subsequent upgrade fails with
    # "type ... already exists". SQLite has no equivalent, so this is a no-op there.
    if op.get_bind().dialect.name == 'postgresql':
        for enum_name in (
            'recommendation_fix_status',
            'recommendation_severity',
            'audit_section_status',
            'audit_section_name',
            'audit_trigger',
            'audit_status',
            'subscription_status',
            'user_plan',
        ):
            op.execute(f'DROP TYPE IF EXISTS {enum_name}')
